### ISSUE TITLE
How to select point in stitching?

### ISSUE THREAD

**Issue by ChristineRYY** [striver13/SurroundViewSystem_Demo#1]
@striver13 Hi, I'm very interested in yowr work. And I debug your code on Ubuntu. 
In stitching process, there are four steps for selecting points of four directions, e.g.,

    cv::imshow("front", mPerspectiveFront);
    cv::waitKey(1);
    while (1)
    {
        int key = cv::waitKey(10);
        cv::setMouseCallback("front", OnMouseAction);
        if (key == 'q')
            break;
    }
    vPstFront = vecTemp;
    vecTemp.clear();
    cv::destroyWindow("front");

How to select point?

**Comment by striver13** [comment]
Hi @ChristineRYY , you should select two points of each direction and then press Q.
For example, I select these two points of front image like this:
![perspectiveFront](https://user-images.githubusercontent.com/40916940/62273647-9a535480-b470-11e9-932a-2aa912a597c2.png)

And i will select two points of right image like this:
![perspectiveRight](https://user-images.githubusercontent.com/40916940/62273664-ab03ca80-b470-11e9-957f-9e747804f08d.png)
